### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [40ants/ci#10]
Building with SBCL 2.2.1 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 494fed6c86af97b503698fcbae1985c86b810401

*40ants-ci-test* fails to build with the following error:

```
; caught ERROR:
;   READ error during COMPILE-FILE: Package ROVE/CORE/ASSERTION does not exist. Line: 77, Column: 77, File-Position: 2593 Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/quicklisp/quicklisp-controller/dist/build-cache/cl-hamcrest/7534bf0d779c99daea0d305254b2f3712544f030/cl-hamcrest-20220210-git/src/rove.lisp" {100A71BD13}>
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001B98003}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "hamcrest/rove" "file-type">

```

[Full log here](http://report.quicklisp.org/2022-02-10/failure-report/ci.html)

**Comment by svetlyak40wt** [comment]
This was an error in the cl-hamcrest. I've fixed it in the https://github.com/40ants/cl-hamcrest/commit/ad512a9bc175cf7c0a4cc95cf98fc33857ba3210 commit.

**Comment by svetlyak40wt** [comment]
@quicklisp could you please recheck with the latest `cl-hamcrest`?
