### ISSUE TITLE
Question: How to generate jobs to test with multiple implementation?

### ISSUE THREAD

**Issue by fstamour** [40ants/ci#7]
Looking at the doc, I don't see if you can generate multiple jobs (one per lisp implementation)?

**Comment by svetlyak40wt** [comment]
Do you want separate jobs or a build matrix?

Here is an example of matrix definition:

```lisp
(defworkflow ci
  :on-push-to "master"
  :by-cron "0 10 * * 1"
  :on-pull-request t
  :cache t
  :jobs ((run-tests
          :os ("ubuntu-latest"
               "macos-latest")
          :quicklisp ("quicklisp"
                      "ultralisp")
          :lisp ("sbcl-bin"
                 "ccl-bin"))))
```

And I belive you can just specify a multiple `run-tests` in the jobs list like this:

```
(defworkflow ci
  :on-push-to "master"
  :by-cron "0 10 * * 1"
  :on-pull-request t
  :cache t
  :jobs ((run-tests :lisp "sbcl-bin")
             (run-tests :lisp "ccl-bin")
             (run-tests :lisp "ecl")))
```

But I didn't tried this way yet. Will try and update the documentation.

Thank you for the question.

**Comment by fstamour** [comment]
Thanks a lot, both examples are useful.

**Comment by svetlyak40wt** [comment]
I found that the second example with multiple jobs didn't work and fixed this issue. Now you can use this feature. Read more [here](https://40ants.com/ci/#x-2840ANTS-CI-3A-3A-40MULTIPLE-JOBS-2040ANTS-DOC-2FLOCATIVES-3ASECTION-29).

Also, now you can use a custom names for jobs and they will look like this:

<img width="375" alt="Screen Shot 2022-01-28 at 23 46 35" src="https://user-images.githubusercontent.com/24827/151619261-2d49e2a6-bc5c-42db-aec5-674d9229a1b0.png">
